# Generated by Django 4.2.16 on 2024-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_joincommunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="joincommunity",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
