# Generated by Django 4.2.16 on 2024-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_joincommunity_updated_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joincommunity",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="community",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
