# Generated by Django 4.2.16 on 2024-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.IntegerField(choices=[(1, "Upvote"), (0, "Downvote")]),
        ),
    ]
