# Generated by Django 4.2.16 on 2024-09-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_vote_vote_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.IntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
    ]
