# Generated by Django 4.2.16 on 2024-09-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_vote_vote_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="User",
            new_name="user",
        ),
    ]
