# Generated by Django 4.2.16 on 2024-09-14 23:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_rename_user_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
